### ISSUE TITLE
Error: Failed to fetch py27-appdirs: Connection time-out

### ISSUE THREAD

**Issue by noloader** [ActiveState/appdirs#102]
I'm a MacPorts user. My PowerMac G5 no longer upgrades due to `appdirs-1.4.3`. The problem has been occurring for several months. See [py27-appdirs: fetch failure](https://trac.macports.org/ticket/55552).

I don't know if i386 or x86_64 Macs have problems with  `appdirs-1.4.3` because I don't use Macs. (I keep the old G5 around for testing software on a big-endian powerpc processor).

As upstream, please work with MacPorts to solve the problems with `appdirs-1.4.3`.

Please forgive me for this bug report. I'm at wit's end trying to solve it. Thank you in advance.

**Comment by zoofood** [comment]
Not issue w/ appdirs and long since closed issue. Cleaning up.
