### ISSUE TITLE
Publish 1.4.4 to pypi

### ISSUE THREAD

**Issue by bkanuka** [ActiveState/appdirs#138]
I'm writing a program that could really use a more recent version of this package - specifically the changes made in https://github.com/ActiveState/appdirs/commit/c99f3303007a1803cbaa23fc2830336ec551460b .
Is there a current timeline on publishing 1.4.4?

Edit: obviously this lib is small enough to just include in my project, but I would like to avoid "static linking" if possible

**Comment by youngquan** [comment]
Approve of release a new version. This packege is really useful and has been used by 43.6k project. It would be nice to make a new release to pypi.

**Comment by zoofood** [comment]
Working on catching up with a series of releases in April and will be on PyPI.
