### ISSUE TITLE
Invalid e-mail in maintainers

### ISSUE THREAD

**Issue by jaraco** [ActiveState/appdirs#142]
The e-mail address `github@srid.name` as [indicated in maintainers](https://github.com/ActiveState/appdirs/blob/f8a8e9dcbdcf212f05e610957ba6ff55294049f0/setup.py#L53) points to a non-existent domain.

```
$ dig srid.name                                                                                                                                           

; <<>> DiG 9.10.6 <<>> srid.name
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 46493
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;srid.name.                     IN      A

;; Query time: 71 msec
;; SERVER: 192.168.162.1#53(192.168.162.1)
;; WHEN: Sun Mar 29 09:49:05 EDT 2020
;; MSG SIZE  rcvd: 38
```

**Comment by McSinyx** [comment]
@srid, are you still maintaining this project?

**Comment by srid** [comment]
No, I don't even use Python anymore.

**Comment by McSinyx** [comment]
@srid, thank you for the prompt response.  My guess is you also don't keep in touch with other maintainer of this project, is it correct?  Is there anyway for us to move forward with many of the issues here, given GH-79?

**Comment by srid** [comment]
@McSinyx I haven't talked to anyone from @ActiveState for years now. Your best bet is to try to get in touch with one of the [activators](https://www.activestate.com/company/careers/).

**Comment by jaraco** [comment]
I've reached out to the maintainers listed in the maintainer_email metadata. I'll let you know if I hear anything.
