### ISSUE TITLE
shoud the shebang "#!/usr/bin/env python" removed from appdirs.py?

### ISSUE THREAD

**Issue by sandy-lcq** [ActiveState/appdirs#145]
On fedora31 docker image,   there is only python3,  and there is no python link to python3,
Error  "python: command not found"  will be reported on this kind of system.

should we remove the shebang or change it to python3?

**Comment by sandy-lcq** [comment]
duplicate https://github.com/pypa/pip/pull/7959

**Comment by McSinyx** [comment]
> duplicate [pypa/pip#7959](https://github.com/pypa/pip/pull/7959)

I think this one is not *the* duplicate.  There's GH-144 to solve this though, and this might be an alternative place for discussion.
