### ISSUE TITLE
Appdirs can return non writable directories

### ISSUE THREAD

**Issue by hmaarrfk** [ActiveState/appdirs#146]
It seems like appdirs can return a directory that cannot be written to.

Is this an expected feature?

https://github.com/scikit-image/scikit-image/issues/4664

From the original user:

> For my flask app's service, the user is a no-login user, and somehow this resolves to /var/www/.
The user doesn't have permissions to create a directory there, so the flask app crashes with a PermissionError raised from.

**Comment by leducvin** [comment]
Leaving a few more details on scikit-image/scikit-image#4664... for my flask app running under user `www-data`, the home directory is `/var/www`. Here is the output of `getent passwd www-data`:

`www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin`

When `appdirs.user_cache_dir()` gets called, it returns `/var/www/.cache`. This is read-only.

**Comment by zoofood** [comment]
Thanks for sending along the information @hmaarrfk and @leducvin. 

Appdirs doesn't do tests of the viability of a directory for writing content to it. It provides what the directory should be according to the XDG spec, effectively $HOME. We would need to add afeature to read the XDG environment variables and you would have to set them to get the result you are after (if I understood what you're doing correctly). This is under consideration, but isn't imminent.

**Comment by hmaarrfk** [comment]
thanks for the confirmation that this is the intended behavior
