### ISSUE TITLE
App name is duplicated on Windows if author name is missing or None

### ISSUE THREAD

**Issue by nyuszika7h** [ActiveState/appdirs#165]
* Python version: 3.9
* appdirs version: 1.4.4

Linux:
```
>>> appdirs.user_data_dir('foo')
'/home/user/.local/share/foo'
```

Windows:
```
>>> appdirs.user_data_dir('foo')
'C:\\Users\\user\\AppData\\Local\\foo\\foo'
```

Specifying an empty string as second argument works to avoid this issue.

**Comment by rlaphoenix** [comment]
It would be great if this got reviewed 👍

**Comment by YariKartoshe4ka** [comment]
Looks like a normal [behavior](https://github.com/ActiveState/appdirs/blob/master/appdirs.py#L77)

**Comment by nyuszika7h** [comment]
Well, maybe it was intended, but I don’t think it makes sense. You shouldn’t force everyone to have two levels of directories if they don’t want to. A lot of programs don’t use a separate folder for author, and often the app name won’t be the author name anyway, so it’s just incorrect.

**Comment by YariKartoshe4ka** [comment]
Noone force you to have two levels of directories if you read the doc string
```
"appauthor" (only used on Windows) is the name of the
            appauthor or distributing body for this application. Typically
            it is the owning company name. This falls back to appname. You may
            pass False to disable it.
```
I think it is not very useful, but it can still help. Also some companies use subderictories e.g.: Mozilla ("Mozilla" dir has subdir "Firefox", Opera ("Opera Software" dir has subdir "Opera Stable" etc)

**Comment by nyuszika7h** [comment]
OK, my bad, I didn’t read that part. That’s still a bit inconsistent, as some distributors like Mozilla will use a directory like `~/.local/share/mozilla` even on Linux, so I don’t see why it’s Windows only. I’m not aware of any Windows standard that requires a separate directory, even if it may be good practice in general.

But personally I don’t want to specify author right now, so maybe that should be a different issue. I was only worried about using `''` as a hack that may stop working in the future, but if setting it to `False` is the officially sanctioned way then I will use that.

**Comment by YariKartoshe4ka** [comment]
I'm not a big Windows connoisseur, but most likely it's just a good tone rule that doesn't have to be followed...
Hack with `''` will be work until `os.path.join` has same bevavior
```python
>>> os.path.join('foo', '', 'bar')
'foo/bar'
```
