### ISSUE TITLE
Add a note directing users to platformdirs

### ISSUE THREAD

**Issue by pradyunsg** [ActiveState/appdirs#170]
https://pypi.org/project/platformdirs/ is a friendly fork, that seems to be much better maintained nowadays.

It would be useful to direct users their way, especially if there aren't maintainance resources available for this project (which seems to be the case based on #79).

**Comment by machow** [comment]
After evaluating both, and reading the issue below I have to admit that I decided to depend on appdirs. I need stronger guarantees about stability of what gets returned (vs correctness).

* https://github.com/platformdirs/platformdirs/issues/47,

**Comment by pradyunsg** [comment]
The problem there isn't that there was any behaviour changes in a minor release (I misread things) but that there's a behaviour change/bugfix compared to what appdirs does. I've updated the issue to reflect that.

Anyway, you're free to use an abandoned-but-functional package. I'm not policing what you do in your projects. :)

**Comment by pradyunsg** [comment]
Thanks @zoofood! ^.^
