### ISSUE TITLE
License parsing

### ISSUE THREAD

**Issue by TechnologyClassroom** [ActiveState/appdirs#180]
GitHub says "View license" in the about section for this package when it could say "MIT license" instead.

I think the issue is that the first line saying "# This is the MIT license" throws off the parser.  If it were changed to "The MIT License (MIT)", I believe it would make it more clear to people visiting for the first time.  Would you like me to make a PR to fix this minor issue?

**Comment by zoofood** [comment]
Good spot. Feel free to submit a PR to get the cred. Cheers.
