### ISSUE TITLE
user_config_dir appends directory name twice in Windows

### ISSUE THREAD

**Issue by JPLeBreton** [ActiveState/appdirs#58]
running the following:
appdirs.user_config_dir('MyApp')

returns:
C:\\Documents and Settings\\username\\Local Settings\\Application Data\\MyApp\\MyApp

expected result:
C:\\Documents and Settings\\username\\Local Settings\\Application Data\\MyApp

**Comment by taers232c** [comment]
For Windows, there is a parameter appauthor, which, if not passed as an argument, is set to appname.
The Windows path is ...\AppName\AppAuthor which is why you got ...\MyApp\MyApp.
By saying appdirs.user_config_dir('MyApp', False) you should get what you want.

**Comment by JPLeBreton** [comment]
Ah, I see, thanks for the clarification, sorry for not reading the docs closely enough.

**Comment by aaaxx** [comment]
What's the rationale for `appauthor` falling back to `appname`? (The MSDN link is dead.)
