### ISSUE TITLE
use freedesktops pyxdg

### ISSUE THREAD

**Issue by elbenfreund** [ActiveState/appdirs#72]
Instead of just extracting the envvar it may be a more robust aproach worth investigating to utilise [pyxdg](https://www.freedesktop.org/wiki/Software/pyxdg/) to handle `XDG` environments .

Then again, it seems like a relatively heavy dependency. My point was to just put it out here in case you were not aware of it.

**Comment by zoofood** [comment]
Thanks for mentioning it I wasn't aware. Greatly appreciated. Will look into it, probably not a dependency we want to add, but I will examine.
