### ISSUE TITLE
site_cache_dir? 

### ISSUE THREAD

**Issue by thorsummoner** [ActiveState/appdirs#77]
I may be mistaken but isn't there a site cache directory on most systems too? Specifically interested in FHS compliant systems, isn't it /var/cache/<app> ?

**Comment by Hacklin** [comment]
No, there is no /var/cache/ .
Just use /var/tmp/ for site_cache_dir.
Like ~/.cache/ the system's /var/tmp/ will survive a reboot.

For inter-process communication (lock files, named pipes, sockets)
you should use XDG_RUNTIME_DIR and fall back to /tmp/ .
XDG_RUNTIME_DIR and /tmp/ may reside in memory and
you _must_not_ place larger files in there.

**Comment by efiop** [comment]
It would still be great to have `site_cache_dir` to standardize it code-wise for all platforms. Windows one doesn't seem obvious at all.

**Comment by efiop** [comment]
If someone else will be looking for this: platformdirs (appdirs fork) now has site_cache_dir https://github.com/platformdirs/platformdirs/pull/145
