### ISSUE TITLE
Circular Dep with setuptools

### ISSUE THREAD

**Issue by cooperlees** [ActiveState/appdirs#87]
Should appdirs support installation/building without setuptools since setuptools now depends on appdirs? Maybe falling back to distutils?

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

This circular dependency is making building in my environment that checks for this much harder and hackier.

**Comment by cooperlees** [comment]
Have upped the following PR:
https://github.com/ActiveState/appdirs/pull/88

**Comment by zoofood** [comment]
Thanks, I will get this out tonight as it sounds like it is critical.

**Comment by cooperlees** [comment]
Awesome - Thanks!

Yeah, massive pain for people like us (Facebook) who build all third party modules from sdsts and have a systems that enforces deps. This circular dep blows it up. We generally do this so we can run unit tests and verify the code is legit etc. :)
