### ISSUE TITLE
With python3.4 in Windows 7 user_config_dir() returns a invalid patch

### ISSUE THREAD

**Issue by williamjmorenor** [ActiveState/appdirs#96]
I have this issue working with python3.4 in Windows 7, the path returned by user_config_dir() if not a valid path, in Python3 strings are unicode so there is not need to scape special caracters.

>>> import appdirs
>>> appdirs.user_config_dir()
'C:\\Users\\Contabilidad\\AppData\\Local'

**Comment by williamjmorenor** [comment]
If I run python appdis.py I got valid paths:

C:\Users\Contabilidad\venv\Scripts\python.exe C:/Users/Contabilidad/PycharmProjects/appdirs/appdirs.py
-- app dirs 1.4.4 --
-- app dirs (with optional 'version')
user_data_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\1.0
user_config_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\1.0
user_cache_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\Cache\1.0
user_state_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\1.0
user_log_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\1.0\Logs
site_data_dir: C:\ProgramData\MyCompany\MyApp\1.0
site_config_dir: C:\ProgramData\MyCompany\MyApp\1.0

-- app dirs (without optional 'version')
user_data_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp
user_config_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp
user_cache_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\Cache
user_state_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp
user_log_dir: C:\Users\Contabilidad\AppData\Local\MyCompany\MyApp\Logs
site_data_dir: C:\ProgramData\MyCompany\MyApp
site_config_dir: C:\ProgramData\MyCompany\MyApp

-- app dirs (without optional 'appauthor')
user_data_dir: C:\Users\Contabilidad\AppData\Local\MyApp\MyApp
user_config_dir: C:\Users\Contabilidad\AppData\Local\MyApp\MyApp
user_cache_dir: C:\Users\Contabilidad\AppData\Local\MyApp\MyApp\Cache
user_state_dir: C:\Users\Contabilidad\AppData\Local\MyApp\MyApp
user_log_dir: C:\Users\Contabilidad\AppData\Local\MyApp\MyApp\Logs
site_data_dir: C:\ProgramData\MyApp\MyApp
site_config_dir: C:\ProgramData\MyApp\MyApp

-- app dirs (with disabled 'appauthor')
user_data_dir: C:\Users\Contabilidad\AppData\Local\MyApp
user_config_dir: C:\Users\Contabilidad\AppData\Local\MyApp
user_cache_dir: C:\Users\Contabilidad\AppData\Local\MyApp\Cache
user_state_dir: C:\Users\Contabilidad\AppData\Local\MyApp
user_log_dir: C:\Users\Contabilidad\AppData\Local\MyApp\Logs
site_data_dir: C:\ProgramData\MyApp
site_config_dir: C:\ProgramData\MyApp

**Comment by williamjmorenor** [comment]
I can not provide a lot of info but even using the AppDirs class i got the same path

dir = appdirs.AppDirs(appname="cacao-accounting", appauthor="Cacao Accounting")
dir.user_config_dir
'C:\\Users\\Contabilidad\\AppData\\Local\\Cacao Accounting\\cacao-accounting'

**Comment by Kriskras99** [comment]
What is exactly the problem? It returns the right path.

**Comment by zoofood** [comment]
Doesn't appear to be an issue. If I'm missing something feel free to ping me again with another explanation. Thanks for using AppDirs though!
