### ISSUE TITLE
Travis CI needs activating

### ISSUE THREAD

**Issue by hugovk** [ActiveState/appdirs#99]
https://travis-ci.org/ActiveState/appdirs says:

![image](https://user-images.githubusercontent.com/1324225/31982572-152bafe2-b962-11e7-91ff-ffc5bc4498ee.png)

> This is not an active repository
>
> You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself.

**Comment by hugovk** [comment]
Travis CI is still inactive.

@zoofood, do you think you could check it? Thank you!

**Comment by zoofood** [comment]
Travis is re-activated.
